version: '3.8'

services:
  silly-demo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app  # Bind mount the current directory
      - /app/vendor
    ports:
      - "8080:8080"  # Expose the app on port 8080
    environment:
      DB_ENDPOINT: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres_password
      DB_NAME: db
    depends_on:
      - postgres
    command: air

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # SQL script to initialize the database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Bind mount nginx configuration
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - silly-demo

volumes:
  postgres_data:  # Declare the volume for PostgreSQL
